((nil . ((cider-clojure-cli-global-options     . "-A:dev:test:build")
         (cider-preferred-build-tool           . clojure-cli)
         (cider-redirect-server-output-to-repl . t)
         (cider-repl-display-help-banner       . nil)
         (cider-repl-init-code                 . ("(go)"))
         (clojure-toplevel-inside-comment-form . t))))
